version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - backend-node-modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - frontend-node-modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  backend-node-modules:
  frontend-node-modules:
