name: Deploy Backend
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: 'contract-checker-dev'
        export_default_credentials: true

    - name: Build and Push Docker image
      run: |
        cd backend
        echo "FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}}" >> .env.production
        echo "FIREBASE_AUTH_DOMAIN=${{secrets.FIREBASE_AUTH_DOMAIN}}" >> .env.production
        echo "FIREBASE_PROJECT_ID=${{secrets.FIREBASE_PROJECT_ID}}" >> .env.production
        echo "FIREBASE_STORAGE_BUCKET=${{secrets.FIREBASE_STORAGE_BUCKET}}" >> .env.production
        echo "FIREBASE_MESSAGING_SENDER_ID=${{secrets.FIREBASE_MESSAGING_SENDER_ID}}" >> .env.production
        echo "FIREBASE_APP_ID=${{secrets.FIREBASE_APP_ID}}" >> .env.production
        echo "FIREBASE_MEASUREMENT_ID=${{secrets.FIREBASE_MEASUREMENT_ID}}" >> .env.production
        echo "OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}" >> .env.production
        gcloud builds submit --tag gcr.io/contract-checker-dev/backend

    - name: Deploy to Cloud Run
      run: gcloud run deploy backend --image gcr.io/contract-checker-dev/backend --platform managed --region asia-northeast1 --set-env-vars NODE_ENV=production --port 5000
